services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\UserIDBundle\Service\UserIdentityServiceImpl:
    public: true

  Tourze\UserIDBundle\Service\UserIdentityService:
    alias: Tourze\UserIDBundle\Service\UserIdentityServiceImpl
    public: true